### ISSUE TITLE
Install failure on OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [drforr/perl6-readline#23]
There are a couple problems with getting this to install on OpenBSD:
- symbols from ncurses need to be loaded before symbols from readline can be used
- some of the symbols the library uses don't exist in the default readline library, but do in ereadline (the readline library installed with pkg or from ports)

I made a [gist](https://gist.github.com/Kaiepi/a2dcaa52b2e7ac4057994c24d0a14b43) with the default test output, test output when loading ncurses symbols, test output when loading ncurses symbols and using ereadline, a diff of the changes I made to get the tests to pass, and the output of `nm -g` for the default readline library, in case they help.

**Comment by drforr** [comment]
Closing as the Perl library now checks the OS it's running on and loads ereadline rather than readline, and uses the code from your gist. Please retest when you get a chance.

**Comment by Kaiepi** [comment]
The install still fails with this error:
```
# Cannot locate native library 'libereadline.so.7': File not found
```
The fix is fairly simple though, I'll pullreq it
