### ISSUE TITLE
 Issues installing on Slackware 14.2 x64 

### ISSUE THREAD

**Issue by ProzacR** [drforr/perl6-readline#24]
I get error:
`===> Testing: Readline:ver<0.0.2>:auth<github:drforr>
 Failed test 'initialize'
 at t/02-base.t line 10
 Cannot locate native library 'libreadline.so': /usr/lib64/libreadline.so: undefined symbol: UP`
And more of them, very similar.
I check for mentioned in error file with:
`$ ls -l /usr/lib64/libreadline.so
lrwxrwxrwx 1 root root 16 Jan 17  2017 /usr/lib64/libreadline.so -> libreadline.so.6`
So I do not know how to fix that.

**Comment by nxadm** [comment]
Would this fix it?

`$ zef install https://github.com/nxadm/perl6-readline.git`

If so, it's the same as #22.

**Comment by ProzacR** [comment]
That gives similar error:
` Failed test 'initialize'
 at t/02-base.t line 10
 Cannot locate native library 'libreadline.so.7': libreadline.so.7: cannot open shared object file: No such file or directory`
I really do not have version 7:
`find /usr/ -iname "libreadlin*"
/usr/lib64/libreadline.so.6.3
/usr/lib64/libreadline.so
/usr/lib64/libreadline.so.6
/usr/lib64/libreadline.so.5
/usr/lib64/libreadline.so.5.2`

**Comment by drforr** [comment]
Closing as the Perl library now checks /usr/lib64 as well as /lib/x86_64-linux-gnu for libreadline-* versions and picks the highest one it finds.
