### ISSUE TITLE
Module fails to install

### ISSUE THREAD

**Issue by vytas-dauksa** [drforr/perl6-readline#3]
Following documentation:
$ panda update && panda install Readline

throws following:
==> Fetching Readline
==> Building Readline
==> Testing Readline
t/01-load.t .. ok
Potential difficulties:
    To pass an array, hash or sub to a function in Perl 6, just pass it as is.
    For other uses of Perl 5's ref operator consider binding with ::= instead.
    Parenthesize as \(...) if you intended a capture of a single variable.
    at /tmp/.panda-work/1449234898_1/t/02-base.t:43
    ------>   my ( $offset, $p-offset ) = ( 0, \⏏$src-offset );
t/02-base.t .. ok
All tests successful.
Files=2, Tests=18, 25 wallclock secs ( 0.02 usr  0.01 sys + 24.59 cusr  0.45 csys = 25.07 CPU)
Result: PASS
==> Installing Readline
Failed to copy '/tmp/.panda-work/1449234898_1/lib/Readline.pm6' to '/home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/97DBD5857C83EDCCEE44FF945B581C15DAB698C3': Failed to copy file: no such file or directory
  in any  at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
  in block  at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/3803F7FE5BF2A5B7D65A002AAFAB1CAE3F4F3E19:54
  in sub indir at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/C9D3DBBE449293E29311B81ADF43623258DDC842:20
  in method install at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/3803F7FE5BF2A5B7D65A002AAFAB1CAE3F4F3E19:41
  in method install at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/707F6C3B206AFCF381257FAD32BED8C7EDADB2E3:146
  in method resolve at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/707F6C3B206AFCF381257FAD32BED8C7EDADB2E3:219
  in sub MAIN at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/resources/3E7064413C5B9F6C0E6D3017B0D3216CBEB1B8C6:18
  in block <unit> at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/resources/3E7064413C5B9F6C0E6D3017B0D3216CBEB1B8C6:146

Actually thrown at:
  in any  at gen/moar/m-Metamodel.nqp:2883
  in block  at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/3803F7FE5BF2A5B7D65A002AAFAB1CAE3F4F3E19:54
  in sub indir at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/C9D3DBBE449293E29311B81ADF43623258DDC842:20
  in method install at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/3803F7FE5BF2A5B7D65A002AAFAB1CAE3F4F3E19:41
  in method install at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/707F6C3B206AFCF381257FAD32BED8C7EDADB2E3:146
  in method resolve at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/sources/707F6C3B206AFCF381257FAD32BED8C7EDADB2E3:219
  in sub MAIN at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/resources/3E7064413C5B9F6C0E6D3017B0D3216CBEB1B8C6:18
  in block <unit> at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/resources/3E7064413C5B9F6C0E6D3017B0D3216CBEB1B8C6:146

Please, consider accepting commit c029773 which might fix this, and see warning too.

**Comment by drforr** [comment]
Sorry, I've been focusing on other perl6 modules. Committed, and will look at the warning later this week.

**Comment by raiph** [comment]
Time to close this issue? (patch has been accepted and the code that raised a warning has been commented out)

**Comment by vytas-dauksa** [comment]
thanks, closing
